services:
  base:
    profiles: ["dontstart"] # Prevent upping, req. profiles: [""] for others
    build:
      context: .
    cap_add:
      - NET_ADMIN
    volumes:
      - /dev/net/tun:/dev/net/tun
    sysctls: # Allow subnetrouter / exit-node
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped

  example-openvpn:
    extends: base
    profiles: [""]
    build:
      args:
        # ! This makes up the name of the vpn config file e.g openvpn-myvpn.conf
        - VPN_TYPE=openvpn
        - VPN_NAME=myvpn # This is also the tailscale node name
    volumes:
      - ./example-data:/var/lib/tailscale # Store tailscale login on restart

    # only if the vpn needs ipv6 (either in connection or forwarding)
    networks:
      - ip6net

networks:
  ip6net:
    external: true
